### ISSUE TITLE
Scan unknown Network

### ISSUE THREAD

**Issue by 2greatsecret** [MatrixEditor/ubnt-discovery-tool#1]
Under Linux Mint 21.2 the tool does not find Ubiquiti devices that are not in the same IP address range.
Is there something extra that needs to be set, or is it a limitation that can be fixed under certain circumstances?
When I am traveling with the notebook, I do not always know the IP addresses of the Ubiquiti devices, so a discovery tool that works across IP address ranges is very helpful.

**Comment by MatrixEditor** [comment]
With `-v` you can enable verbose mode and list all actions taken on received packets. By default, this tool queries for Ubiquity devices on a special multicast address (IPv4 and IPv6) on all local network interfaces. If there are no devices responding within 10s, they won't be listed (both gui and cli mode).

Please tell me if you can see whether any packets are received using the verbose mode.

**Comment by 2greatsecret** [comment]
I have now carried out a few tests and can report the following:
1. only LAN enabled (WiFi off) I have no chance of finding anything at all.

```
Wifi OFF

ifconfig 
enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 169.254.42.10  netmask 255.255.0.0  broadcast 169.254.255.255
        ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 250  bytes 39118 (39.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 694  bytes 113337 (113.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf3900000-f3920000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 8093  bytes 973300 (973.3 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8093  bytes 973300 (973.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether yy:yy:yy:yy:yy:yy  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



java -jar ubnt-discovery-tool-1.3.3-UI.jar -cli -v 9
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer bind
WARNUNG: [IDS]::Bind(Kein passendes Gerät gefunden)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer bind
WARNUNG: [IDS]::Bind(Kein passendes Gerät gefunden)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer bind
WARNUNG: [IDS]::Bind(Kein passendes Gerät gefunden)
Nov. 30, 2023 11:15:27 AM com.ubnt.discovery.UbntDiscoveryTool$CLI run
INFORMATION: Starting to receive Packets...
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:15:27 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Exception in thread "Thread-1" java.lang.IllegalArgumentException
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1303)
	at java.base/java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1189)
	at java.base/java.util.concurrent.Executors.newFixedThreadPool(Executors.java:92)
	at com.ubnt.net.IDiscoveryServer.run(IDiscoveryServer.java:216)
	at java.base/java.lang.Thread.run(Thread.java:833)
Nov. 30, 2023 11:15:37 AM com.ubnt.discovery.UbntDiscoveryTool$CLI nextSecond
INFORMATION: [CLI] Finished receiving packets! (Got 0 service[s])
Nov. 30, 2023 11:15:37 AM com.ubnt.discovery.UbntDiscoveryTool$CLI displayServices
WARNUNG: [CLI] Could not resolve any UbntServices with filter: 

```

2. LAN and WiFi activated finds nothing if any IP address is entered on the LAN interface that does not match the IP address range of the antenna.

```
wiFi ON

ifconfig
VLAN: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::902b:611a:67b9:47ce  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 21  bytes 3361 (3.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.255.200  netmask 255.255.255.0  broadcast 10.10.255.255
        ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 463  bytes 72766 (72.7 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1616  bytes 277875 (277.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf3900000-f3920000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 43027  bytes 3721031 (3.7 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 43027  bytes 3721031 (3.7 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether yy:yy:yy:yy:yy:yy  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.48.90  netmask 255.255.252.0  broadcast 192.168.51.255
        inet6 fe80::2c02:91e8:f4bd:801  prefixlen 64  scopeid 0x20<link>
        ether zz:zz:zz:zz:zz:zz  txqueuelen 1000  (Ethernet)
        RX packets 52397  bytes 42318941 (42.3 MB)
        RX errors 0  dropped 3088  overruns 0  frame 0
        TX packets 21565  bytes 4150493 (4.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0




java -jar ubnt-discovery-tool-1.3.3-UI.jar -cli -v 9
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x0]::Bind(success=/192.168.122.1:42064, interface=virbr0)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x1]::Bind(success=/192.168.48.90:38521, interface=wlp3s0)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x2]::Bind(success=/10.10.255.200:49003, interface=enp0s25)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x3]::Bind(success=/0:0:0:0:0:0:0:0:43331, interface=null)
Nov. 30, 2023 11:24:55 AM com.ubnt.discovery.UbntDiscoveryTool$CLI run
INFORMATION: Starting to receive Packets...
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x0]::Send(from=/192.168.122.1 to=/255.255.255.255:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x1]::Send(from=/192.168.48.90 to=/255.255.255.255:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x2]::Send(from=/10.10.255.200 to=/255.255.255.255:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x0]::Send(from=/192.168.122.1 to=/255.255.255.255:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x1]::Send(from=/192.168.48.90 to=/255.255.255.255:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x2]::Send(from=/10.10.255.200 to=/255.255.255.255:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x3]::Send(from=/0:0:0:0:0:0:0:0 to=/[ff02:0:0:0:0:0:0:1]:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x3]::Send(from=/0:0:0:0:0:0:0:0 to=/[ff02:0:0:0:0:0:0:1]:10001)
Nov. 30, 2023 11:24:55 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:24:56 AM com.ubnt.net.IDiscoveryServer run
INFORMATION: [IDS]::Run(channelCount=4)
Nov. 30, 2023 11:25:06 AM com.ubnt.discovery.UbntDiscoveryTool$CLI nextSecond
INFORMATION: [CLI] Finished receiving packets! (Got 0 service[s])
Nov. 30, 2023 11:25:06 AM com.ubnt.discovery.UbntDiscoveryTool$CLI displayServices
WARNUNG: [CLI] Could not resolve any UbntServices with filter: 
```


3. LAN and WiFi activated, IP address in the IP address range of the antenna (192.168.1.0/24, 169.254.0.0/16(?)) works at least with one antenna. What it would look like if several antennas were accessible but had different IP address ranges.

```
WiFi ON same IP-Address range as UniFi defice on LAN

enp0s25: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.22  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::4619:8055:d40e:5568  prefixlen 64  scopeid 0x20<link>
        ether xX:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 539  bytes 84527 (84.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2421  bytes 449833 (449.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf3900000-f3920000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 45322  bytes 3945659 (3.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 45322  bytes 3945659 (3.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether yy:yy:yy:yy:yy:yy  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp3s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.48.90  netmask 255.255.252.0  broadcast 192.168.51.255
        inet6 fe80::2c02:91e8:f4bd:801  prefixlen 64  scopeid 0x20<link>
        ether zz:zz:zz:zz:zz:zz  txqueuelen 1000  (Ethernet)
        RX packets 54555  bytes 42746361 (42.7 MB)
        RX errors 0  dropped 3407  overruns 0  frame 0
        TX packets 22329  bytes 4380194 (4.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


java -jar ubnt-discovery-tool-1.3.3-UI.jar -cli -v 9
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x0]::Bind(success=/192.168.122.1:50484, interface=virbr0)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x1]::Bind(success=/192.168.48.90:35896, interface=wlp3s0)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x2]::Bind(success=/10.100.179.22:54995, interface=enp0s25)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x3]::Bind(success=/10.0.171.154:40242, interface=enp0s25)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x4]::Bind(success=/10.0.174.54:44303, interface=enp0s25)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x5]::Bind(success=/10.0.168.254:34538, interface=enp0s25)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x6]::Bind(success=/192.168.1.22:44367, interface=enp0s25)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x7]::Bind(success=/0:0:0:0:0:0:0:0:38322, interface=null)
Nov. 30, 2023 11:31:34 AM com.ubnt.discovery.UbntDiscoveryTool$CLI run
INFORMATION: Starting to receive Packets...
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x0]::Send(from=/192.168.122.1 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x1]::Send(from=/192.168.48.90 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x2]::Send(from=/10.100.179.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x3]::Send(from=/10.0.171.154 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x4]::Send(from=/10.0.174.54 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x5]::Send(from=/10.0.168.254 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x6]::Send(from=/192.168.1.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x0]::Send(from=/192.168.122.1 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x1]::Send(from=/192.168.48.90 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x2]::Send(from=/10.100.179.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x3]::Send(from=/10.0.171.154 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x4]::Send(from=/10.0.174.54 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x5]::Send(from=/10.0.168.254 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x6]::Send(from=/192.168.1.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x7]::Send(from=/0:0:0:0:0:0:0:0 to=/[ff02:0:0:0:0:0:0:1]:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x7]::Send(from=/0:0:0:0:0:0:0:0 to=/[ff02:0:0:0:0:0:0:1]:10001)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer run
INFORMATION: [IDS]::Run(channelCount=8)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer lambda$listen$0
INFORMATION: [IDS@0x6]::Listen(from=/192.168.1.20): Received Packet with length: 134
Nov. 30, 2023 11:31:34 AM com.ubnt.net.UbntDiscoveryServer parsePacket
INFORMATION: [UDS]::ParsePacket(v=0x1, rawLength=1024, from=/192.168.1.20)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.BaseServiceParser parse
INFORMATION: [ASP]::Parse(Parsing packet; 134 bytes)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.BaseServiceParser parse
INFORMATION: [ASP]::Parse(dataLength=130)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.BaseServiceParser parse
INFORMATION: [ASP]::Parse(success)
Nov. 30, 2023 11:31:34 AM com.ubnt.net.IDiscoveryServer lambda$listen$0
INFORMATION: [IDS@0x6]::Listen(newService at /192.168.1.20)
Nov. 30, 2023 11:31:34 AM com.ubnt.discovery.UbntDiscoveryTool$CLI onServiceLocated
INFORMATION: [CLI] Received Discovery Response from /192.168.1.20
Nov. 30, 2023 11:31:34 AM com.ubnt.discovery.UbntDiscoveryTool$CLI onServiceLocated
INFORMATION: [CLI] Added new Service with MAC/Address: 80:2A:A8:XX:YY:ZZ
Nov. 30, 2023 11:31:44 AM com.ubnt.discovery.UbntDiscoveryTool$CLI nextSecond
INFORMATION: [CLI] Finished receiving packets! (Got 1 service[s])
Nov. 30, 2023 11:31:44 AM com.ubnt.discovery.UbntDiscoveryTool$CLI displayServices
INFORMATION: [CLI] Got 1 services to display!
============ 'NanoStation M5' v0x001@enp0s25 ============
       IPINFO (0x2): IpInfo{mac='80:2A:A8:XX:YY:ZZ', ip='192.168.1.20'}
   HW_ADDRESS (0x1): 1.2.3.4
       UPTIME (0xa): 1907
     HOSTNAME (0xb): NanoStation M5
     PLATFORM (0xc): N5N
        ESSID (0xd): ubnt
    WIFI_MODE (0xe): 2
     LOCATING (0x18): false
   FW_VERSION (0x3): XW.ar934x.v6.3.11.33396.230425.1644
       WEB_UI (0x10): 59477
        MODEL (0x14): NanoStation M5


java -jar ubnt-discovery-tool-1.3.3-UI.jar -v 9
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x0]::Bind(success=/192.168.122.1:34281, interface=virbr0)
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x1]::Bind(success=/192.168.48.90:36915, interface=wlp3s0)
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x2]::Bind(success=/10.100.179.22:41478, interface=enp0s25)
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x3]::Bind(success=/10.0.171.154:54125, interface=enp0s25)
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x4]::Bind(success=/10.0.174.54:53275, interface=enp0s25)
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x5]::Bind(success=/10.0.168.254:33815, interface=enp0s25)
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x6]::Bind(success=/192.168.1.22:34235, interface=enp0s25)
Nov. 30, 2023 11:32:59 AM com.ubnt.net.IDiscoveryServer bind
INFORMATION: [IDS@0x7]::Bind(success=/0:0:0:0:0:0:0:0:46508, interface=null)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x0]::Send(from=/192.168.122.1 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x1]::Send(from=/192.168.48.90 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x2]::Send(from=/10.100.179.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x3]::Send(from=/10.0.171.154 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x4]::Send(from=/10.0.174.54 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x5]::Send(from=/10.0.168.254 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x6]::Send(from=/192.168.1.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x0]::Send(from=/192.168.122.1 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x1]::Send(from=/192.168.48.90 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x2]::Send(from=/10.100.179.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x3]::Send(from=/10.0.171.154 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x4]::Send(from=/10.0.174.54 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x5]::Send(from=/10.0.168.254 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x6]::Send(from=/192.168.1.22 to=/255.255.255.255:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x7]::Send(from=/0:0:0:0:0:0:0:0 to=/[ff02:0:0:0:0:0:0:1]:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(start)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS@0x7]::Send(from=/0:0:0:0:0:0:0:0 to=/[ff02:0:0:0:0:0:0:1]:10001)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer send
INFORMATION: [IDS]::Send(end)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer run
INFORMATION: [IDS]::Run(channelCount=8)
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer lambda$listen$0
INFORMATION: [IDS@0x6]::Listen(from=/192.168.1.20): Received Packet with length: 147
Nov. 30, 2023 11:33:03 AM com.ubnt.net.IDiscoveryServer lambda$listen$0
INFORMATION: [IDS@0x6]::Listen(newService at /192.168.1.20)
```

**Comment by 2greatsecret** [comment]
I have found the solution (for me): 
`sudo ip link set dev enp0s25 promisc on`

On Linux mint, promiscuous mode are maybe not enabled by default.

**Comment by 2greatsecret** [comment]
Is there a possibility that the program itself activates the promiscuous mode at startup and deactivates it again at exit, or should this be done with a start script for the tool?

**Comment by MatrixEditor** [comment]
In my opinion this is an important information which should be included in the documentation. But it is also an external, system dependent issue, which is why I most likely won't implement a workaround. As you proposed a script is the best alternative.
